name: Docker Compose Test

on:
  push:
    paths:
      - 'CompUGE-Backend/**'
  pull_request:
    paths:
      - 'CompUGE-Backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Compose
      run: docker compose up -d

    - name: Wait for the backend to be ready
      run: sleep 60

    - name: Test the FastAPI app
      run: |
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:15564/ping)
        echo "Response code: $RESPONSE"
        if [ "$RESPONSE" == "200" ]; then 
          echo "Ping test passed";
        else
          echo "Ping test failed";
          exit 1;
        fi
    - name: Get backend service logs
      if: failure()
      run: docker compose logs backend
    - name: Get db service logs
      if: failure()
      run: docker compose logs db
    - name: Stop and remove Docker Compose services
      run: docker-compose down

