version: '3.0'

services:
  backend:
    build: .
    restart: always
    ports:
      - "15564:8000"
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
      - "5432"
    ports:
      - "15565:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local